export const international = {
  ru: {
    date: {
      year: 'г',
      month: 'мес',
    },
    sections: {
      experience: 'Опыт',
      skills: 'Технологии',
    },
    labels: {
      birthday: 'Дата рождения:',
      location: 'Локация:',
      formatFork: 'Формат работы:',
      contacts: 'Контакты:',
      repository: 'Репозитории:',
    },
    tooltip: {
      one: '- знаком поверхностно',
      two: '- знаком, есть опыт работы',
      three: '- уверенный опыт владения',
      four: '- продвинутый опыт владения',
    },
    firstname: 'Иван',
    lastname: 'Крылов',
    middlename: 'Александрович',
    location: 'Mосковская область, Пушкино',
    formatWoks: 'Удаленно, гибрид',
    endDate: 'по настоящее время',
    responsibilities: [
      'Принятие ключевых архитектурных решений и определение стратегического направления развития проекта',
      'Ответственность за качество кода, стабильность и своевременные релизы веб-приложения',
      'Выполнение роли тимлида в команде из трёх разработчиков: распределение задач, ревью кода, менторство',
      'Разработка и контроль выполнения плана миграции Vue-приложения на актуальную версию фреймворка',
      'Масштабирование приложения: инициирование и успешное объединение двух React-репозиториев в единую архитектуру',
      'Разработка функциональных разделов административной панели с высокой сложностью бизнес-логики',
      'Создание плагина на основе WebRTC для обработки видеопотоков в реальном времени',
      'Разработка микросервиса на Node.js для генерации PDF-документов',
      'Повышение качества кодовой базы за счёт системной реорганизации и оптимизации существующего кода',
      'Работа с безопасностью: реализация мер по защите клиентского приложения от XSS и CSRF атак, включая настройку политики безопасности, валидацию и санитизацию данных',
      'Участие в формировании продуктовых решений: активное взаимодействие с аналитиками, дизайнерами и бэкенд-разработчиками для повышения качества требований, ускорения постановки задач и оптимизации реализации функционала',
    ],
  },
  eng: {
    date: {
      year: 'y',
      month: 'm',
    },
    sections: {
      experience: 'Experience',
      skills: 'Technologies',
    },
    labels: {
      birthday: 'Birthday:',
      location: 'Location:',
      formatFork: 'Work format:',
      contacts: 'Contacts:',
      repository: 'Repositories:',
    },
    tooltip: {
      one: '- basic familiarity',
      two: '- familiar, some work experience',
      three: '- confident experience',
      four: '- advanced experience',
    },
    firstname: 'Ivan',
    lastname: 'Krylov',
    middlename: 'Aleksandrovich',
    location: 'Pushkino, Moscow Region',
    formatWoks: 'Remote, hybrid',
    endDate: 'present',
    responsibilities: [
      'Making key architectural decisions and defining the strategic direction of the project',
      'Responsibility for code quality, stability and timely releases of the web application',
      'Performing the role of a team lead in a team of three developers: distributing tasks, code review, mentoring',
      'Development and control of the migration plan of the Vue-application to the current version of the framework',
      'Application scaling: initiation and successful integration of two React repositories into a single architecture',
      'Development of functional sections of the administrative panel with high complexity of business logic',
      'Creating a WebRTC-based plugin for real-time video stream processing',
      'Development of a microservice in Node.js for generating PDF documents',
      'Improving the quality of the codebase through systematic reorganization and optimization of existing code',
      'Security work: implementation of measures to protect the client application from XSS and CSRF attacks, including setting up a security policy, validation and data sanitization',
      'Participation in the formation of product solutions: active interaction with analysts, designers and backend developers to improve the quality of requirements, accelerate task setting and optimize the implementation of functionality',
    ],
  },
};
